import React from 'react';
import { Product, Category, CustomerReview } from './types';

export const COLORS = {
  primary: '#002C51',
  secondary: '#FF6B00',
  dark: '#000D1A',
  text: '#F8FAFC'
};

export const CONTACT_INFO = {
  whatsapp: '5585999608799',
  phoneDisplay: '(85) 99960-8799',
  instagramFortaleza: '@oticacdo_fortaleza',
  instagramCaucaia: '@oticacdo_caucaia'
};

export const REVIEWS: CustomerReview[] = [
  {
    id: 'r1',
    name: 'Nanda Rodrigues',
    location: 'Fortaleza, CE',
    text: 'A armação da Ótica CDO superou completamente minhas expectativas, confesso que estava meio receosa no começo, mas o atendimento foi tão bom, o consultor realmente se preocupava com o que eu queria e não que o que seria melhor pra ele, Obrigada!',
    imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/Nanda%20Rodrigues.png?raw=true',
    rating: 5
  },
  {
    id: 'r2',
    name: 'Ricardo Oliveira',
    location: 'Caucaia, CE',
    text: 'Minhas lentes estão perfeias. O site ajudou a entender qual era o melhor índice para o meu grau.',
    imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/Ricardo%20Oliveira.png?raw=true',
    rating: 5
  },
  {
    id: 'r3',
    name: 'Juliana Costa',
    location: 'Fortaleza, CE',
    text: 'Adorei o site me ajudou bastante. Vcs merecem muito o crescimento, sério!.',
    imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/Juliana%20Costa.png?raw=true',
    rating: 5
  }
];

export const PRODUCTS: Product[] = [
  // --- ARMAÇÕES CLAIRE AGUILAR (CA1 - CA42) ---
  { id: 'CA1', name: 'Claire Aguilar - Élégance', category: Category.FRAMES, description: 'Luxo contemporâneo com acabamento cristalino.', price: 129.90, imageUrl: 'https://raw.githubusercontent.com/MarceloGomes-Dev/CDO/35e2b2be07004a6ee28335472506aebaabf89627/10.png', brand: 'CA', tags: ['Acetato', 'Luxo'], gender: 'Feminino', frameColor: 'Preto', material: 'Acetato Premium', measurements: '54-18-145', likes: 124, rating: 5 },
  { id: 'CA2', name: 'Claire Aguilar - Prestige', category: Category.FRAMES, description: 'Design refinado com detalhes em dourado.', price: 149.90, imageUrl: 'https://raw.githubusercontent.com/MarceloGomes-Dev/CDO/35e2b2be07004a6ee28335472506aebaabf89627/11.png', brand: 'CA', tags: ['Metal', 'Luxo'], gender: 'Feminino', frameColor: 'Dourado', material: 'Metal Noble', measurements: '52-17-140', likes: 156, rating: 5 },
  { id: 'CA3', name: 'Claire Aguilar - Exquis Black', category: Category.FRAMES, description: 'Leveza e resistência aerodinâmica.', price: 129.90, imageUrl: 'https://raw.githubusercontent.com/MarceloGomes-Dev/CDO/35e2b2be07004a6ee28335472506aebaabf89627/3.png', brand: 'CA', tags: ['Titânio', 'Moderno'], gender: 'Feminino', frameColor: 'Preto', material: 'Titânio Aero', measurements: '53-19-142', likes: 92, rating: 5 },
  { id: 'CA4', name: 'Claire Aguilar - Moonlight', category: Category.FRAMES, description: 'Tons de marfim inspirados na luz da lua.', price: 79.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/15.png?raw=true', brand: 'CA', tags: ['Acetato', 'Elegante'], onSale: true, gender: 'Feminino', frameColor: 'Marfim', material: 'Acetato', measurements: '51-18-138', likes: 78, rating: 4 },
  { id: 'CA5', name: 'Claire Aguilar - Allure', category: Category.FRAMES, description: 'Combinação de beleza e durabilidade.', price: 79.90, imageUrl: 'https://raw.githubusercontent.com/MarceloGomes-Dev/CDO/35e2b2be07004a6ee28335472506aebaabf89627/1.png', brand: 'CA', tags: ['Titânio', 'Quadrado'], gender: 'Feminino', frameColor: 'Tartaruga', material: 'Titânio Noble', measurements: '54-17-145', likes: 89, rating: 5 },
  { id: 'CA6', name: 'Claire Aguilar - Pure', category: Category.FRAMES, description: 'Design clássico e sofisticado.', price: 159.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/16.png?raw=true', brand: 'CA', tags: ['Acetato', 'Quadrado'], gender: 'Feminino', frameColor: 'Preto', material: 'Acetato', measurements: '52-18-140', likes: 45, rating: 4 },
  { id: 'CA7', name: 'Claire Aguilar - Urban', category: Category.FRAMES, description: 'Estilo sofisticado com leveza.', price: 74.90, originalPrice: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/14.png?raw=true', brand: 'CA', tags: ['Classic', 'Sale'], onSale: true, gender: 'Unissex', frameColor: 'Marrom', material: 'Acetato', measurements: '53-17-142', likes: 177, rating: 5 },
  { id: 'CA8', name: 'Claire Aguilar - Classic', category: Category.FRAMES, description: 'Ideal para uso diário prolongado.', price: 74.90, originalPrice: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/12.png?raw=true', brand: 'CA', tags: ['Metal', 'Gatinho'], onSale: true, gender: 'Feminino', frameColor: 'Marrom', material: 'Titânio', measurements: '52-16-138', likes: 127, rating: 5 },
  { id: 'CA9', name: 'Claire Aguilar - Focus', category: Category.FRAMES, description: 'Elegância e design atemporal.', price: 74.90, originalPrice: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/13.png?raw=true', brand: 'CA', tags: ['Redondo'], gender: 'Feminino', frameColor: 'Preto', material: 'Acetato', measurements: '50-19-140', likes: 112, rating: 5 },
  { id: 'CA10', name: 'Claire Aguilar - Line', category: Category.FRAMES, description: 'Personalidade e bom gosto.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/17.png?raw=true', brand: 'CA', tags: ['Redondo'], onSale: true, gender: 'Feminino', frameColor: 'Marrom', material: 'Acetato', measurements: '51-20-142', likes: 102, rating: 5 },
  { id: 'CA11', name: 'Claire Aguilar - Haute', category: Category.FRAMES, description: 'Metal leve e sofisticado.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/37.png?raw=true', brand: 'CA', tags: ['Metal', 'Redondo'], gender: 'Feminino', frameColor: 'Vermelha', material: 'Metal', measurements: '50-20-140', likes: 202, rating: 5 },
  { id: 'CA12', name: 'Claire Aguilar - Absolute', category: Category.FRAMES, description: 'Visual minimalista premium.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/39.png?raw=true', brand: 'CA', tags: ['Acetato', 'Minimalista'], gender: 'Unissex', frameColor: 'Preto e Bege', material: 'Acetato', measurements: '53-18-142', likes: 282, rating: 5 },
  { id: 'CA13', name: 'Claire Aguilar - Vision', category: Category.FRAMES, description: 'Leveza e sofisticação.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/40.png?raw=true', brand: 'CA', tags: ['Metal'], gender: 'Feminino', frameColor: 'Vermelha', material: 'Metal', measurements: '52-19-140', likes: 202, rating: 5 },
  { id: 'CA14', name: 'Claire Aguilar - Prime', category: Category.FRAMES, description: 'Metal leve e sofisticado.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/41.png?raw=true', brand: 'CA', tags: ['Metal'], gender: 'Feminino', frameColor: 'Vermelha', material: 'Metal', measurements: '51-19-140', likes: 202, rating: 5 },
  { id: 'CA15', name: 'Claire Aguilar - Elite', category: Category.FRAMES, description: 'Metal leve e sofisticado.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/42.png?raw=true', brand: 'CA', tags: ['Metal'], gender: 'Feminino', frameColor: 'Vermelha', material: 'Metal', measurements: '53-17-138', likes: 202, rating: 5 },
  { id: 'CA18', name: 'Claire Aguilar - Focus Blue', category: Category.FRAMES, description: 'Metal leve e sofisticado.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/18.png?raw=true', brand: 'CA', tags: ['Metal'], gender: 'Feminino', frameColor: 'Azul', material: 'Metal', measurements: '51-21-140', likes: 202, rating: 5 },
  { id: 'CA22', name: 'Claire Aguilar - CatEye', category: Category.FRAMES, description: 'Estilo gatinha clássico.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/25.png?raw=true', brand: 'CA', tags: ['Acetato'], gender: 'Feminino', frameColor: 'Preto', material: 'Acetato', measurements: '54-16-140', likes: 202, rating: 5 },
  { id: 'CA24', name: 'Claire Aguilar - OneFocus', category: Category.FRAMES, description: 'Design marcante e robusto.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/27.png?raw=true', brand: 'CA', tags: ['Acetato'], gender: 'Feminino', frameColor: 'Preto', material: 'Acetato', measurements: '55-18-145', likes: 292, rating: 5 },
  { id: 'CA29', name: 'Claire Aguilar - Flowers', category: Category.FRAMES, description: 'Visual elegante sem exageros.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/32.png?raw=true', brand: 'Up', tags: ['Acetato'], gender: 'Feminino', frameColor: 'Preta e Vermelha', material: 'Acetato', measurements: '54-17-142', likes: 302, rating: 5 },
  { id: 'CA33', name: 'Claire Aguilar - Focus Pink', category: Category.FRAMES, description: 'Conforto e estilo.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/43.png?raw=true', brand: 'CA', tags: ['Acetato'], gender: 'Feminino', frameColor: 'Rosa', material: 'Acetato', measurements: '52-17-138', likes: 342, rating: 5 },
  { id: 'CA34', name: 'Claire Aguilar - Finess', category: Category.FRAMES, description: 'Estilo minimalista atemporal.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/44.png?raw=true', brand: 'CA', tags: ['Acetato'], gender: 'Feminino', frameColor: 'Nude', material: 'Acetato', measurements: '53-18-142', likes: 287, rating: 5 },
  { id: 'CA35', name: 'Claire Aguilar - LightNight', category: Category.FRAMES, description: 'Leveza extrema.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/45.png?raw=true', brand: 'CA', tags: ['Acetato'], gender: 'Unissex', frameColor: 'Transparente', material: 'Acetato', measurements: '51-19-140', likes: 144, rating: 5 },
  { id: 'CA36', name: 'Claire Aguilar - Purple', category: Category.FRAMES, description: 'Visual discreto.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/47.png?raw=true', brand: 'CA', tags: ['Acetato'], gender: 'Feminino', frameColor: 'Lilás', material: 'Acetato', measurements: '52-18-142', likes: 302, rating: 5 },
  { id: 'CA40', name: 'Claire Aguilar - Soft Brown', category: Category.FRAMES, description: 'Elegância equilibrada.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/50.png?raw=true', brand: 'CA', tags: ['Acetato'], gender: 'Feminino', frameColor: 'Marrom', material: 'Acetato', measurements: '54-17-145', likes: 202, rating: 5 },
  { id: 'CA41', name: 'Claire Aguilar - Passion Red', category: Category.FRAMES, description: 'Estilo moderno vibrante.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/51.png?raw=true', brand: 'CA', tags: ['Acetato'], gender: 'Feminino', frameColor: 'Vermelha', material: 'Acetato', measurements: '53-18-142', likes: 362, rating: 5 },
  { id: 'CA42', name: 'Claire Aguilar - Mixed Texture', category: Category.FRAMES, description: 'Visual autêntico.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/52.png?raw=true', brand: 'CA', tags: ['Acetato'], gender: 'Feminino', frameColor: 'Mesclado', material: 'Acetato', measurements: '52-19-140', likes: 195, rating: 5 },
  { id: 'CA45', name: 'Masculina Oakley Style', category: Category.FRAMES, description: 'Metal de alta performance.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/55.png?raw=true', brand: 'Oakley', tags: ['Masculino', 'Metal'], gender: 'Masculino', frameColor: 'Prata', material: 'Metal', measurements: '56-18-145', likes: 235, rating: 5 },
  { id: 'CA46', name: 'KidzUp Flex Black', category: Category.FRAMES, description: 'Estilo clássico infantil.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/56.png?raw=true', brand: 'CA', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Preto', material: 'Acetato', measurements: '46-16-125', likes: 321, rating: 5 },
  { id: 'CA47', name: 'KidzUp Square Black', category: Category.FRAMES, description: 'Conforto e resistência infantil.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/57.png?raw=true', brand: 'CA', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Preto', material: 'Acetato', measurements: '48-15-130', likes: 195, rating: 5 },
  { id: 'CA48', name: 'KidzUp Pure White', category: Category.FRAMES, description: 'Design leve e divertido.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/58.png?raw=true', brand: 'CA', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Branco', material: 'Acetato', measurements: '47-17-128', likes: 195, rating: 5 },
  { id: 'CA49', name: 'KidzUp Metal Junior', category: Category.FRAMES, description: 'Estrutura reforçada infantil.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/59.png?raw=true', brand: 'CA', tags: ['Infantil', 'Metal'], gender: 'Masculino', frameColor: 'Preto', material: 'Metal', measurements: '49-18-135', likes: 195, rating: 5 },
  { id: 'CA59', name: 'Claire Aguilar - Rimless Gold', category: Category.FRAMES, description: 'Visual sofisticado sem bordas.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/72.png?raw=true', brand: 'CA', tags: ['Parafusada'], gender: 'Feminino', frameColor: 'Metal', material: 'Parafusada', measurements: '53-18-140', likes: 195, rating: 5 },

  // --- ARMAÇÕES UP (UP17 - UP80) ---
  { id: 'UP17', name: 'KidzUp Flex Green', category: Category.FRAMES, description: 'Flexibilidade total infantil.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/19.png?raw=true', brand: 'Up', tags: ['Infantil', 'Flexível'], gender: 'Infantil', frameColor: 'Verde', material: 'Acetato', measurements: '46-15-125', likes: 102, rating: 5 },
  { id: 'UP19', name: 'KidzUp Sky Blue', category: Category.FRAMES, description: 'Conforto e diversão.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/20.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Azul', material: 'Acetato', measurements: '48-16-130', likes: 202, rating: 5 },
  { id: 'UP20', name: 'KidzUp Red Fire', category: Category.FRAMES, description: 'Segurança absoluta.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/21.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Vermelha', material: 'Acetato', measurements: '47-17-128', likes: 172, rating: 5 },
  { id: 'UP21', name: 'KidzUp Citrus Mix', category: Category.FRAMES, description: 'Design vibrante.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/22.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Azul e Laranja', material: 'Acetato', measurements: '48-18-132', likes: 252, rating: 5 },
  { id: 'UP23', name: 'KidzUp Deep Sea', category: Category.FRAMES, description: 'Aventura visual.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/26.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Blue Sky', material: 'Acetato', measurements: '46-16-125', likes: 202, rating: 5 },
  { id: 'UP25', name: 'Up Casuality Business', category: Category.FRAMES, description: 'Estilo executivo.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/28.png?raw=true', brand: 'Up', tags: ['Masculino'], gender: 'Masculino', frameColor: 'Preto', material: 'Metal', measurements: '55-17-145', likes: 159, rating: 5 },
  { id: 'UP26', name: 'KidzUp Duo Color', category: Category.FRAMES, description: 'Estilo em dose dupla.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/29.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Preto e Vermelho', material: 'Acetato', measurements: '47-16-128', likes: 106, rating: 5 },
  { id: 'UP27', name: 'Up Unity Bronze', category: Category.FRAMES, description: 'Harmonia unissex.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/30.png?raw=true', brand: 'Up', tags: ['Metal', 'Unissex'], gender: 'Unissex', frameColor: 'Marrom', material: 'Metal', measurements: '52-19-140', likes: 133, rating: 5 },
  { id: 'UP28', name: 'Up Air Tech Blue', category: Category.FRAMES, description: 'Engenharia de leveza.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/31.png?raw=true', brand: 'Up', tags: ['Acetato', 'Masculino'], gender: 'Masculino', frameColor: 'Azul', material: 'Acetato', measurements: '54-18-142', likes: 182, rating: 5 },
  { id: 'UP30', name: 'KidzUp Active Red', category: Category.FRAMES, description: 'Para crianças em movimento.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/21.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Vermelha', material: 'Acetato', measurements: '47-17-128', likes: 402, rating: 5 },
  { id: 'UP31', name: 'Up Blossom Pink', category: Category.FRAMES, description: 'Delicadeza e conforto.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/36.png?raw=true', brand: 'Up', tags: ['Acetato'], gender: 'Feminino', frameColor: 'Rosa', material: 'Acetato', measurements: '52-18-140', likes: 357, rating: 5 },
  { id: 'UP32', name: 'Up Translucity Crystal', category: Category.FRAMES, description: 'Design invisível.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/38.png?raw=true', brand: 'Up', tags: ['Acetato'], gender: 'Feminino', frameColor: 'Trasparente', material: 'Acetato', measurements: '53-17-142', likes: 299, rating: 5 },
  { id: 'UP37', name: 'KidzUp Sport Red', category: Category.FRAMES, description: 'Resistência esportiva.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/46.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Vermelha', material: 'Acetato', measurements: '48-15-130', likes: 202, rating: 5 },
  { id: 'UP38', name: 'Up Silver Lining', category: Category.FRAMES, description: 'Prata Nobre.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/48.png?raw=true', brand: 'Up', tags: ['Metal', 'Masculino'], gender: 'Masculino', frameColor: 'Prata', material: 'Metal', measurements: '54-18-145', likes: 159, rating: 5 },
  { id: 'UP39', name: 'Up Round Silver', category: Category.FRAMES, description: 'Geometria perfeita.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/49.png?raw=true', brand: 'Up', tags: ['Metal', 'Unissex'], gender: 'Unissex', frameColor: 'Prata', material: 'Metal', measurements: '50-20-140', likes: 488, rating: 5 },
  { id: 'UP43', name: 'Up Tortoise Elite', category: Category.FRAMES, description: 'Luxo clássico.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/53.png?raw=true', brand: 'Up', tags: ['Acetato', 'Masculino'], gender: 'Masculino', frameColor: 'Marrom', material: 'Acetato', measurements: '55-17-145', likes: 301, rating: 5 },
  { id: 'UP44', name: 'Up Matte Grey', category: Category.FRAMES, description: 'Textura moderna.', price: 149.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/54.png?raw=true', brand: 'Up', tags: ['Acetato', 'Masculino'], gender: 'Masculino', frameColor: 'Cinza', material: 'Acetato', measurements: '54-18-142', likes: 377, rating: 5 },
  { id: 'UP50', name: 'KidzUp Soft Pink', category: Category.FRAMES, description: 'Delicadeza infantil.', price: 137.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/60.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Rosa', material: 'Acetato', measurements: '46-16-125', likes: 195, rating: 5 },
  { id: 'UP51', name: 'KidzUp Sunny Yellow', category: Category.FRAMES, description: 'Luz e alegria.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/61.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Amarelo', material: 'Acetato', measurements: '47-15-128', likes: 195, rating: 5 },
  { id: 'UP52', name: 'KidzUp Dark Night', category: Category.FRAMES, description: 'Estilo marcante.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/62.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Preto', material: 'Acetato', measurements: '48-17-130', likes: 195, rating: 5 },
  { id: 'UP53', name: 'Up Navy Classic', category: Category.FRAMES, description: 'Azul profundo.', price: 153.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/63.png?raw=true', brand: 'UP', tags: ['Acetato', 'Masculino'], gender: 'Masculino', frameColor: 'Azul', material: 'Acetato', measurements: '55-18-145', likes: 195, rating: 5 },
  { id: 'UP54', name: 'KidzUp Lemonade', category: Category.FRAMES, description: 'Cor e frescor.', price: 154.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/64.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Amarelo', material: 'Acetato', measurements: '47-18-128', likes: 195, rating: 5 },
  { id: 'UP55', name: 'KidzUp Ash Grey', category: Category.FRAMES, description: 'Neutralidade.', price: 155.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/65.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Cinza', material: 'Acetato', measurements: '48-16-130', likes: 195, rating: 5 },
  { id: 'UP55_2', name: 'KidzUp Pro Bio', category: Category.FRAMES, description: 'Material sustentável.', price: 156.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/66.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Preto e Verde', material: 'Acetato', measurements: '49-17-132', likes: 195, rating: 5 },
  { id: 'UP56', name: 'KidzUp Core Black', category: Category.FRAMES, description: 'Essencial.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/67.png?raw=true', brand: 'UP', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Preto', material: 'Acetato', measurements: '47-15-125', likes: 195, rating: 5 },
  { id: 'UP57', name: 'KidzUp Bright Red', category: Category.FRAMES, description: 'Energia visual.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/69.png?raw=true', brand: 'Up', tags: ['Infantil'], gender: 'Infantil', frameColor: 'Vermelho', material: 'Acetato', measurements: '48-16-128', likes: 195, rating: 5 },
  { id: 'UP58', name: 'Up Metal Noir', category: Category.FRAMES, description: 'Preto fosco.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/70.png?raw=true', brand: 'Up', tags: ['Metal', 'Unissex'], gender: 'Unissex', frameColor: 'Preto', material: 'Metal', measurements: '50-19-140', likes: 195, rating: 5 },
  { id: 'UP58_2', name: 'Claire Aguilar - Signature Rimless', category: Category.FRAMES, description: 'Arquitetura de leveza.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/71.png?raw=true', brand: 'CA', tags: ['Parafusada'], gender: 'Feminino', frameColor: 'Metal', material: 'Parafusada', measurements: '53-17-138', likes: 195, rating: 5 },
  { id: 'UP60', name: 'Up Executive Prime', category: Category.FRAMES, description: 'Status e precisão.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/73.png?raw=true', brand: 'Up', tags: ['Parafusada', 'Masculino'], gender: 'Masculino', frameColor: 'Preto', material: 'Parafusada', measurements: '54-18-145', likes: 195, rating: 5 },
  { id: 'UP61', name: 'Up Prestige Edition', category: Category.FRAMES, description: 'Edição limitada.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/74.png?raw=true', brand: 'Up', tags: ['Parafusada', 'Masculino'], gender: 'Masculino', frameColor: 'Preto', material: 'Parafusada', measurements: '55-17-142', likes: 195, rating: 5 },
  { id: 'UP62', name: 'Up Golden Ratio', category: Category.FRAMES, description: 'Proporção áurea.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/75.png?raw=true', brand: 'Up', tags: ['Metal', 'Unissex'], gender: 'Unissex', frameColor: 'Dourado', material: 'Metal', measurements: '51-20-140', likes: 195, rating: 5 },
  { id: 'UP63', name: 'Up Silver Hybrid', category: Category.FRAMES, description: 'Mix de materiais.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/76.png?raw=true', brand: 'UP', tags: ['Metal', 'Masculino'], gender: 'Masculino', frameColor: 'Prata', material: 'Metal e Acetato', measurements: '54-18-142', likes: 195, rating: 5 },
  { id: 'UP64', name: 'Up CK Inspired', category: Category.FRAMES, description: 'Tendência global.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/77.png?raw=true', brand: 'CK', tags: ['Metal', 'Masculino'], gender: 'Masculino', frameColor: 'Prata', material: 'Metal e Acetato', measurements: '55-17-145', likes: 195, rating: 5 },
  { id: 'UP65', name: 'Up Snow White', category: Category.FRAMES, description: 'Brancura absoluta.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/78.png?raw=true', brand: 'Up', tags: ['Metal', 'Unissex'], gender: 'Unissex', frameColor: 'Branco', material: 'Metal', measurements: '50-19-140', likes: 195, rating: 5 },
  { id: 'UP66', name: 'Up Starlight Gliter', category: Category.FRAMES, description: 'Glamour ótico.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/79.png?raw=true', brand: 'Up', tags: ['Metal', 'Feminino'], gender: 'Feminino', frameColor: 'Gliter', material: 'Metal, nylon', measurements: '51-21-140', likes: 195, rating: 5 },
  { id: 'UP65_2', name: 'Up Black Knight', category: Category.FRAMES, description: 'Resistência extrema.', price: 152.90, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/80.png?raw=true', brand: 'Up', tags: ['Metal', 'Masculino'], gender: 'Masculino', frameColor: 'preto', material: 'Metal', measurements: '54-17-145', likes: 195, rating: 5 },

  // --- LENTES TÉCNICAS (L1 - L12) ---
  { id: 'l1', name: 'Lentes V.S Resina Standard AR', category: Category.LENSES, description: 'Lentes indicadas para uso casual sem intensidades ao celular.', price: 120.00, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/VS-AR.png?raw=true', brand: 'Par', tags: ['Monofocal', '1.49', 'Econômica'], material: 'Índice 1.49', sphRange: '+4.00 a -4.00', cylRange: 'Até -2.00', likes: 210, rating: 5 },
  { id: 'l2', name: 'Lentes V.S Resina Blue Cut AR', category: Category.LENSES, description: 'Lentes indicadas para uso intenso ao celular e computador.', price: 179.00, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/VS-AR-blue.png?raw=true', brand: 'Par', tags: ['Monofocal', '1.49', 'Filtro Azul'], material: 'Índice 1.49', sphRange: '+4.00 a -6.00', cylRange: 'Até -2.00', likes: 210, rating: 5 },
  { id: 'l3', name: 'Lentes V.S Resina Photo + AR', category: Category.LENSES, description: 'Lentes indicadas para uso com exposição ao sol.', price: 299.00, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/VS-AR-Foto.png?raw=true', brand: 'Par', tags: ['Monofocal', '1.49', 'Fotossensível'], material: 'Índice 1.49', sphRange: '+4.00 a -4.00', cylRange: 'Até -2.00', likes: 210, rating: 5 },
  { id: 'l4', name: 'Lentes V.S Resina Photo Blue Cut', category: Category.LENSES, description: 'O máximo em conforto: sol + digital.', price: 359.00, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/VS-FOTO-AR-blue.png?raw=true', brand: 'Par', tags: ['Monofocal', '1.49', 'Premium Digital'], material: 'Índice 1.49', sphRange: '+4.00 a -6.00', cylRange: 'Até -2.00', likes: 210, rating: 5 },
  { id: 'l5', name: 'Lentes V.S Poli Antirreflexo', category: Category.LENSES, description: 'Lentes duráveis com 1 ano de garantia contra quebra.', price: 199.00, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/VS-AR-POLI.png?raw=true', brand: 'Par', tags: ['Monofocal', '1.59', 'Policarbonato'], material: 'Índice 1.59', sphRange: '+4.00 a -6.00', cylRange: 'Até -2.00', likes: 210, rating: 5 },
  { id: 'l6', name: 'Lentes V.S Poli Blue Cut AR', category: Category.LENSES, description: 'Resistência extrema com filtro azul.', price: 259.00, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/VS-Poli-AR-blue.png?raw=true', brand: 'Par', tags: ['Monofocal', '1.59', 'Policarbonato'], material: 'Índice 1.59', sphRange: '+4.00 a -6.00', cylRange: 'Até -2.00', likes: 210, rating: 5 },
  { id: 'l7', name: 'Lentes V.S Poli Photo AR', category: Category.LENSES, description: 'Indestrutíveis e adaptáveis ao sol.', price: 559.00, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/7VS-Poli-FotoAR.png?raw=true', brand: 'Par', tags: ['Monofocal', '1.49', 'Fotossensível'], material: 'Índice 1.49', sphRange: '+4.00 a -4.00', cylRange: 'Até -2.00', likes: 210, rating: 5 },
  { id: 'l8', name: 'Lentes V.S Poli Photo Blue Cut', category: Category.LENSES, description: 'A lente definitiva para visão simples.', price: 750.00, imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/VS-Poli-AR-Foto.png?raw=true', brand: 'Varilux', tags: ['Progressiva', '1.74', 'Elite'], material: 'Índice 1.74', sphRange: 'Sob Medida', cylRange: 'Até -4.00', addRange: '+0.75 a +3.50', likes: 210, rating: 5 },
  { id: 'l9', name: 'Lentes Varilux Series XR', category: Category.LENSES, description: 'Lente multifocal assistida por IA.', price: 'Sob Consulta', imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/Varilux.png?raw=true', brand: 'Varilux', tags: ['Progressiva', 'Premium', 'IA'], material: '1.50 a 1.74', sphRange: 'Customizada', cylRange: 'Customizada', addRange: 'Até +3.50', likes: 512, rating: 5 },
  { id: 'l10', name: 'Lentes Zeiss Precision Smart', category: Category.LENSES, description: 'Tecnologia Zeiss para o mundo conectado.', price: 'Sob Consulta', imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/Zeiss.png?raw=true', brand: 'Zeiss', tags: ['Progressiva', 'Precisão', 'Digital'], material: '1.50 a 1.74', sphRange: 'Customizada', cylRange: 'Customizada', addRange: 'Até +3.50', likes: 410, rating: 5 },
  { id: 'l11', name: 'Lentes Hoya Vision Premium', category: Category.LENSES, description: 'Conforto visual extremo.', price: 'Sob Consulta', imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/Hoya.png?raw=true', brand: 'Hoya', tags: ['Progressiva', 'Premium'], material: '1.50 a 1.74', sphRange: 'Customizada', cylRange: 'Customizada', addRange: 'Até +3.50', likes: 320, rating: 5 },
  { id: 'l12', name: 'Lentes Kodak Precise Digital', category: Category.LENSES, description: 'Tradição com nitidez digital.', price: 'Sob Consulta', imageUrl: 'https://github.com/MarceloGomes-Dev/CDO/blob/main/Kodak.png?raw=true', brand: 'Kodak', tags: ['Progressiva', 'Tradição'], material: '1.50 a 1.74', sphRange: 'Customizada', cylRange: 'Customizada', addRange: 'Até +3.00', likes: 210, rating: 5 },

  // --- ACESSÓRIOS ---
  { id: 'a1', name: 'Limpador de Lentes Spray 60ml', category: Category.ACCESSORIES, description: 'Solução premium para limpeza de lentes.', price: 25.00, imageUrl: 'https://images.unsplash.com/photo-1605333396915-47ed6b68a00e?auto=format&fit=crop&q=80&w=600', brand: 'CDO', tags: ['Limpeza'], material: 'Fluido Antiestático', likes: 332, rating: 5 }
];

export const LogoIcon = () => (
  <div className="w-10 h-10 md:w-12 md:h-12 flex items-center justify-center">
    <img
      src="https://raw.githubusercontent.com/MarceloGomes-Dev/oticaCDO/main/Logo.png"
      alt="Ótica Cdo Logo"
      className="max-w-full max-h-full object-contain"
    />
  </div>
);